
import java.util.Scanner;
import ui.TextUI;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        System.out.println(getGreeting());
        Scanner scanner = new Scanner(System.in);
        TextUI ui = new TextUI(scanner);
        ui.launch();
    }
    
    public static String getGreeting(){
        return "Welcome to the CS literature recommendation system!";
    }
}
